version: "2"

services:
    nginx:
        image: nginx:1.13
        ports:
                - "8080:80"
        volumes_from:
            - freeboard:ro
    freeboard:
        image: freeboard
        build: .
